"""Read capability declarations out of a blueprint's `config` JSON.

Capabilities are declared under `config["capabilities"]`. That is where a blueprint already says
what a range contains -- networks, VMs, MSEL, router -- so it needs no migration and no new column,
which matters under CLAUDE.md architecture rule 4.

Every error here names the capability and the field. A blueprint is hand-edited and
machine-generated by turns, and "invalid capability" with no index is a bad half-hour.

This is also where the chart repository a blueprint names is checked against what the install
permits. A blueprint is authored over the API, and the repository it names is handed to
helm-controller, which fetches it and reconciles whatever chart it finds; so the repository is a
trust decision and it has to be made somewhere an author cannot reach. It is made here rather than
in the API route because the route is not the only way in -- the catalog installer and the seeder
build specs from config too, and a check they skip is not a check.
"""

from __future__ import annotations

from collections.abc import Mapping, Sequence
from dataclasses import dataclass
from typing import Any
from urllib.parse import unquote, urlsplit

from .models import Scope
from .runtime import CapabilitySpec, ChartRef, HookSpec, ImageRef, WebSpec

__all__ = [
    "REPOSITORY_SCHEMES",
    "REPOSITORY_SETTING",
    "ChartRepositoryPolicy",
    "capabilities_from_blueprint_config",
    "capability_from_config",
    "is_repository_url",
    "repository_policy",
]

# The setting an operator adds a repository to. Named here because every refusal quotes it: being
# told "not permitted" without being told where permission is granted is a dead end.
REPOSITORY_SETTING = "capability_chart_repositories"

# The only two schemes that are a chart repository at all. `http://` is a cleartext fetch anyone
# on the path can answer, and `file://` points source-controller at its own filesystem rather
# than at a repository.
REPOSITORY_SCHEMES = ("https", "oci")


@dataclass(frozen=True, slots=True)
class ChartRepositoryPolicy:
    """Which chart repositories a blueprint on this install may name.

    **Empty permits none, and that is the default.** Air-gap is a constraint now rather than
    later (ADR-0007): an install has no runtime dependency on a public registry, so the
    repositories it can reach are a short list somebody configured on purpose, and anything else
    is a refusal. Defaulting the other way -- everything allowed until an operator denies it --
    is what let any account that could POST a blueprint choose a chart for helm-controller to
    render and apply with the permissions Flux holds.

    An entry covers itself and everything under it: `https://charts.example/stable` is permitted
    by an entry of `https://charts.example`. Scheme and host must match exactly, so neither
    `https://charts.example.evil.test` nor `https://charts.example@evil.test` is under it, and a
    path carrying a `..` segment is not a repository at all, because the server would resolve it
    back out of the entry it appears to sit under.
    """

    allowed: tuple[str, ...] = ()

    def permits(self, repository: str) -> bool:
        candidate = _split_repository(repository)
        if candidate is None:
            return False
        return any(_covers(_split_repository(entry), candidate) for entry in self.allowed)

    def require(self, repository: str, where: str) -> None:
        """Raise unless `repository` is permitted, saying which it was and how to allow it."""
        if self.permits(repository):
            return
        if _split_repository(repository) is None:
            schemes = " or ".join(f"{s}://" for s in REPOSITORY_SCHEMES)
            raise ValueError(
                f"{where} names chart repository {repository!r}, which is not a chart repository "
                f"this platform fetches from: a {schemes} URL, with a host, and no '.' or '..' "
                f"in its path. Adding it to {REPOSITORY_SETTING} would not make it one"
            )
        if not self.allowed:
            raise ValueError(
                f"{where} names chart repository {repository!r}, and this install permits no "
                f"chart repositories: list the ones a blueprint may name in {REPOSITORY_SETTING} "
                "(comma-separated). Nothing is permitted until one is."
            )
        raise ValueError(
            f"{where} names chart repository {repository!r}, which this install does not permit. "
            f"Permitted: {', '.join(self.allowed)}. Add it to {REPOSITORY_SETTING} to allow it."
        )


def repository_policy() -> ChartRepositoryPolicy:
    """The policy this install is configured with."""
    # Imported inside the function on purpose. `proving_ground.capability` is the licence
    # boundary (ADR-0011) and importing the contract must not drag the engine's settings in
    # behind it, but which repositories an install trusts is an install-level decision and has
    # nowhere else to come from. A caller that wants no engine configuration at all passes its
    # own policy to the functions below.
    from ..config import get_settings

    settings = get_settings()
    # Read by name rather than as an attribute so that an install whose settings predate the
    # setting denies everything, which is the conservative answer, instead of failing every
    # blueprint parse with AttributeError.
    configured = str(getattr(settings, REPOSITORY_SETTING, "") or "")
    entries = [entry.strip() for entry in configured.split(",") if entry.strip()]
    # The repository this install already trusts to deliver the platform itself is permitted
    # without being named twice. An air-gapped install mirrors every chart into one registry and
    # points `chart_repository` at it; making the operator restate it is a trap, not a control.
    # Only when it is a repository URL in its own right, though: the chart ships
    # `chart_repository` as a scheme-less OCI path, because api/kubernetes_update.py splits a
    # registry host off the front of it. Carrying that into the allow-list permits nothing while
    # making every refusal name it as permitted, and hides the refusal that says which setting
    # to fix.
    platform = str(getattr(settings, "chart_repository", "") or "").strip()
    if is_repository_url(platform):
        entries.append(platform)
    return ChartRepositoryPolicy(allowed=tuple(dict.fromkeys(entries)))


def is_repository_url(url: str) -> bool:
    """True when `url` is the shape of a chart repository this platform would fetch from."""
    return _split_repository(url) is not None


def capabilities_from_blueprint_config(
    config: Mapping[str, Any] | None, *, policy: ChartRepositoryPolicy | None = None
) -> list[CapabilitySpec]:
    """Parse every capability a blueprint declares. A blueprint declaring none is valid."""
    declared = (config or {}).get("capabilities") or []
    if not isinstance(declared, Sequence) or isinstance(declared, (str, bytes)):
        raise ValueError("blueprint config 'capabilities' must be a list")
    if not declared:
        return []
    policy = policy or repository_policy()
    return [
        capability_from_config(entry, index=i, policy=policy) for i, entry in enumerate(declared)
    ]


def capability_from_config(
    entry: Any, *, index: int | None = None, policy: ChartRepositoryPolicy | None = None
) -> CapabilitySpec:
    where = f"capabilities[{index}]" if index is not None else "capability"
    if not isinstance(entry, Mapping):
        raise ValueError(f"{where} must be an object")

    name = _require(entry, "name", where)
    where = f"capability {name!r}"

    raw_scope = _require(entry, "scope", where)
    try:
        scope = Scope(raw_scope)
    except ValueError:
        allowed = ", ".join(s.value for s in Scope)
        raise ValueError(
            f"{where} has scope {raw_scope!r}; must be one of {allowed} -- there is no default"
        ) from None

    chart = _require(entry, "chart", where)
    if not isinstance(chart, Mapping):
        raise ValueError(f"{where} 'chart' must be an object")

    hooks = entry.get("hooks") or {}
    if not isinstance(hooks, Mapping):
        raise ValueError(f"{where} 'hooks' must be an object")
    if "verify" not in hooks:
        # A capability you cannot verify teaches nothing you can evidence.
        raise ValueError(f"{where} must declare a verify hook")

    spec = CapabilitySpec(
        name=name,
        version=str(_require(entry, "version", where)),
        chart=ChartRef(
            name=str(_require(chart, "name", f"{where} chart")),
            version=str(_require(chart, "version", f"{where} chart")),
            repository=str(_require(chart, "repository", f"{where} chart")),
        ),
        scope=scope,
        verify=_hook(hooks["verify"], f"{where} verify hook"),
        seed=_hook(hooks["seed"], f"{where} seed hook") if hooks.get("seed") else None,
        reset=_hook(hooks["reset"], f"{where} reset hook") if hooks.get("reset") else None,
        images=tuple(ImageRef(str(i)) for i in entry.get("images") or ()),
        values=dict(entry.get("values") or {}),
        web=_web(entry.get("web"), f"{where} web") if entry.get("web") else None,
    )
    if "/" in spec.chart.name or spec.chart.name in (".", ".."):
        # Against an OCI registry the chart name is appended to the repository URL, so a name
        # carrying a path addresses a chart the allow-list entry never covered -- the repository
        # would pass the check below while the chart came from somewhere else on that registry.
        # Against an HTTP repository it is a key in `index.yaml` and a path is meaningless there.
        raise ValueError(
            f"{where} chart has name {spec.chart.name!r}; a chart name is one segment, not a "
            "path -- where the chart comes from is the repository field's to say"
        )
    # Last, so that a blueprint with several things wrong hears about its own mistakes before it
    # hears about the install's policy -- but before the spec is returned, so no caller can get
    # one this install would refuse to install.
    (policy or repository_policy()).require(spec.chart.repository, f"{where} chart")
    return spec


def _split_repository(url: str) -> tuple[str, str, str] | None:
    """(scheme, host, path) for a chart repository URL, or None when it is not one.

    Host carries its port and its userinfo if any, so that comparison against an allow-list entry
    is exact: `https://charts.example@evil.test` has host `charts.example@evil.test`, which is not
    `charts.example` and must not be read as it.
    """
    parts = urlsplit(str(url).strip())
    if parts.scheme.lower() not in REPOSITORY_SCHEMES or not parts.netloc:
        return None
    if parts.query or parts.fragment:
        return None
    path = parts.path.rstrip("/")
    # A `..` segment is how an entry naming one directory is made to cover its siblings: the
    # prefix match below reads `/approved/../unapproved` as sitting under `/approved`, while the
    # server resolving the request reads it as `/unapproved`. Refused rather than collapsed,
    # because the URL that would reach the cluster is the one the blueprint wrote, not the one
    # this function normalised. Unquoted first: a server that decodes before it resolves would
    # treat `%2e%2e` the same way.
    if any(unquote(segment) in (".", "..") for segment in path.split("/")):
        return None
    return parts.scheme.lower(), parts.netloc.lower(), path


def _covers(allowed: tuple[str, str, str] | None, candidate: tuple[str, str, str]) -> bool:
    if allowed is None:
        return False
    if allowed[:2] != candidate[:2]:
        return False
    # At a path boundary: an entry of `/stable` covers `/stable/charts` and not `/stable-mirror`.
    return candidate[2] == allowed[2] or candidate[2].startswith(f"{allowed[2]}/")


def _web(raw: Any, where: str) -> WebSpec:
    if not isinstance(raw, Mapping):
        raise ValueError(f"{where} must be an object with 'service' and 'port'")
    return WebSpec(
        service=str(_require(raw, "service", where)),
        port=int(_require(raw, "port", where)),
        path=str(raw.get("path") or "/"),
    )


def _hook(raw: Any, where: str) -> HookSpec:
    if not isinstance(raw, Mapping):
        raise ValueError(f"{where} must be an object")
    command = _require(raw, "command", where)
    if isinstance(command, str) or not isinstance(command, Sequence):
        raise ValueError(f"{where} 'command' must be a list of arguments, not a shell string")
    return HookSpec(
        image=ImageRef(str(_require(raw, "image", where))),
        command=tuple(str(a) for a in command),
        timeout_seconds=int(raw.get("timeout_seconds", 300)),
    )


def _require(source: Mapping[str, Any], key: str, where: str) -> Any:
    if key not in source or source[key] in (None, ""):
        raise ValueError(f"{where} is missing required field {key!r}")
    return source[key]
